[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@vercel/og"]

[[edge_functions]]
  function = "social-meta"
  path = "/global-consensus/*"

[[edge_functions]]
  function = "social-meta"
  path = "/audit-target/*"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  framework = "#custom"
  autoLaunch = false
