/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmissionsRouteImport } from './routes/submissions'
import { Route as ScorecardRouteImport } from './routes/scorecard'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyRouteImport } from './routes/my'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as ContributorsRouteImport } from './routes/contributors'
import { Route as BetaWaitlistRouteImport } from './routes/beta-waitlist'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LandingRouteImport } from './routes/_landing'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as LandingIndexRouteImport } from './routes/_landing.index'
import { Route as ScoringTargetIdRouteImport } from './routes/scoring.$targetId'
import { Route as ProfileSubmissionsRouteImport } from './routes/profile/submissions'
import { Route as ProfileSettingsRouteImport } from './routes/profile/settings'
import { Route as ProfilePrivacyRouteImport } from './routes/profile/privacy'
import { Route as ProfilePreferencesRouteImport } from './routes/profile/preferences'
import { Route as ContributorsGovernanceRouteImport } from './routes/contributors/governance'
import { Route as LandingManifestoRouteImport } from './routes/_landing.manifesto'
import { Route as MySubmissionsIndexRouteImport } from './routes/my/submissions.index'
import { Route as LandingGlobalConsensusIndexRouteImport } from './routes/_landing.global-consensus.index'
import { Route as SubmissionsTargetIdRouteImport } from './routes/submissions/target.$id'
import { Route as SubmissionsRfcIdRouteImport } from './routes/submissions/rfc.$id'
import { Route as LandingGlobalConsensusSlugRouteImport } from './routes/_landing.global-consensus.$slug'
import { Route as LandingAuditTargetSlugRouteImport } from './routes/_landing.audit-target.$slug'
import { Route as ShareScorecardTargetIdUserIdRouteImport } from './routes/share.scorecard.$targetId.$userId'

const SubmissionsRoute = SubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorecardRoute = ScorecardRouteImport.update({
  id: '/scorecard',
  path: '/scorecard',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoute = MyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorsRoute = ContributorsRouteImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaWaitlistRoute = BetaWaitlistRouteImport.update({
  id: '/beta-waitlist',
  path: '/beta-waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRoute,
} as any)
const ScoringTargetIdRoute = ScoringTargetIdRouteImport.update({
  id: '/scoring/$targetId',
  path: '/scoring/$targetId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSubmissionsRoute = ProfileSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfilePrivacyRoute = ProfilePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfilePreferencesRoute = ProfilePreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => ProfileRoute,
} as any)
const ContributorsGovernanceRoute = ContributorsGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => ContributorsRoute,
} as any)
const LandingManifestoRoute = LandingManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => LandingRoute,
} as any)
const MySubmissionsIndexRoute = MySubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => MyRoute,
} as any)
const LandingGlobalConsensusIndexRoute =
  LandingGlobalConsensusIndexRouteImport.update({
    id: '/global-consensus/',
    path: '/global-consensus/',
    getParentRoute: () => LandingRoute,
  } as any)
const SubmissionsTargetIdRoute = SubmissionsTargetIdRouteImport.update({
  id: '/target/$id',
  path: '/target/$id',
  getParentRoute: () => SubmissionsRoute,
} as any)
const SubmissionsRfcIdRoute = SubmissionsRfcIdRouteImport.update({
  id: '/rfc/$id',
  path: '/rfc/$id',
  getParentRoute: () => SubmissionsRoute,
} as any)
const LandingGlobalConsensusSlugRoute =
  LandingGlobalConsensusSlugRouteImport.update({
    id: '/global-consensus/$slug',
    path: '/global-consensus/$slug',
    getParentRoute: () => LandingRoute,
  } as any)
const LandingAuditTargetSlugRoute = LandingAuditTargetSlugRouteImport.update({
  id: '/audit-target/$slug',
  path: '/audit-target/$slug',
  getParentRoute: () => LandingRoute,
} as any)
const ShareScorecardTargetIdUserIdRoute =
  ShareScorecardTargetIdUserIdRouteImport.update({
    id: '/share/scorecard/$targetId/$userId',
    path: '/share/scorecard/$targetId/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/beta-waitlist': typeof BetaWaitlistRoute
  '/contributors': typeof ContributorsRouteWithChildren
  '/governance': typeof GovernanceRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/my': typeof MyRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/review': typeof ReviewRoute
  '/scorecard': typeof ScorecardRoute
  '/submissions': typeof SubmissionsRouteWithChildren
  '/manifesto': typeof LandingManifestoRoute
  '/contributors/governance': typeof ContributorsGovernanceRoute
  '/profile/preferences': typeof ProfilePreferencesRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/submissions': typeof ProfileSubmissionsRoute
  '/scoring/$targetId': typeof ScoringTargetIdRoute
  '/': typeof LandingIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/audit-target/$slug': typeof LandingAuditTargetSlugRoute
  '/global-consensus/$slug': typeof LandingGlobalConsensusSlugRoute
  '/submissions/rfc/$id': typeof SubmissionsRfcIdRoute
  '/submissions/target/$id': typeof SubmissionsTargetIdRoute
  '/global-consensus': typeof LandingGlobalConsensusIndexRoute
  '/my/submissions': typeof MySubmissionsIndexRoute
  '/share/scorecard/$targetId/$userId': typeof ShareScorecardTargetIdUserIdRoute
}
export interface FileRoutesByTo {
  '/beta-waitlist': typeof BetaWaitlistRoute
  '/contributors': typeof ContributorsRouteWithChildren
  '/governance': typeof GovernanceRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/my': typeof MyRouteWithChildren
  '/review': typeof ReviewRoute
  '/scorecard': typeof ScorecardRoute
  '/submissions': typeof SubmissionsRouteWithChildren
  '/manifesto': typeof LandingManifestoRoute
  '/contributors/governance': typeof ContributorsGovernanceRoute
  '/profile/preferences': typeof ProfilePreferencesRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/submissions': typeof ProfileSubmissionsRoute
  '/scoring/$targetId': typeof ScoringTargetIdRoute
  '/': typeof LandingIndexRoute
  '/admin': typeof AdminIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/audit-target/$slug': typeof LandingAuditTargetSlugRoute
  '/global-consensus/$slug': typeof LandingGlobalConsensusSlugRoute
  '/submissions/rfc/$id': typeof SubmissionsRfcIdRoute
  '/submissions/target/$id': typeof SubmissionsTargetIdRoute
  '/global-consensus': typeof LandingGlobalConsensusIndexRoute
  '/my/submissions': typeof MySubmissionsIndexRoute
  '/share/scorecard/$targetId/$userId': typeof ShareScorecardTargetIdUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_landing': typeof LandingRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/beta-waitlist': typeof BetaWaitlistRoute
  '/contributors': typeof ContributorsRouteWithChildren
  '/governance': typeof GovernanceRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/my': typeof MyRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/review': typeof ReviewRoute
  '/scorecard': typeof ScorecardRoute
  '/submissions': typeof SubmissionsRouteWithChildren
  '/_landing/manifesto': typeof LandingManifestoRoute
  '/contributors/governance': typeof ContributorsGovernanceRoute
  '/profile/preferences': typeof ProfilePreferencesRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/submissions': typeof ProfileSubmissionsRoute
  '/scoring/$targetId': typeof ScoringTargetIdRoute
  '/_landing/': typeof LandingIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/_landing/audit-target/$slug': typeof LandingAuditTargetSlugRoute
  '/_landing/global-consensus/$slug': typeof LandingGlobalConsensusSlugRoute
  '/submissions/rfc/$id': typeof SubmissionsRfcIdRoute
  '/submissions/target/$id': typeof SubmissionsTargetIdRoute
  '/_landing/global-consensus/': typeof LandingGlobalConsensusIndexRoute
  '/my/submissions/': typeof MySubmissionsIndexRoute
  '/share/scorecard/$targetId/$userId': typeof ShareScorecardTargetIdUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/beta-waitlist'
    | '/contributors'
    | '/governance'
    | '/login'
    | '/logout'
    | '/my'
    | '/profile'
    | '/review'
    | '/scorecard'
    | '/submissions'
    | '/manifesto'
    | '/contributors/governance'
    | '/profile/preferences'
    | '/profile/privacy'
    | '/profile/settings'
    | '/profile/submissions'
    | '/scoring/$targetId'
    | '/'
    | '/admin/'
    | '/profile/'
    | '/audit-target/$slug'
    | '/global-consensus/$slug'
    | '/submissions/rfc/$id'
    | '/submissions/target/$id'
    | '/global-consensus'
    | '/my/submissions'
    | '/share/scorecard/$targetId/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/beta-waitlist'
    | '/contributors'
    | '/governance'
    | '/login'
    | '/logout'
    | '/my'
    | '/review'
    | '/scorecard'
    | '/submissions'
    | '/manifesto'
    | '/contributors/governance'
    | '/profile/preferences'
    | '/profile/privacy'
    | '/profile/settings'
    | '/profile/submissions'
    | '/scoring/$targetId'
    | '/'
    | '/admin'
    | '/profile'
    | '/audit-target/$slug'
    | '/global-consensus/$slug'
    | '/submissions/rfc/$id'
    | '/submissions/target/$id'
    | '/global-consensus'
    | '/my/submissions'
    | '/share/scorecard/$targetId/$userId'
  id:
    | '__root__'
    | '/_landing'
    | '/admin'
    | '/beta-waitlist'
    | '/contributors'
    | '/governance'
    | '/login'
    | '/logout'
    | '/my'
    | '/profile'
    | '/review'
    | '/scorecard'
    | '/submissions'
    | '/_landing/manifesto'
    | '/contributors/governance'
    | '/profile/preferences'
    | '/profile/privacy'
    | '/profile/settings'
    | '/profile/submissions'
    | '/scoring/$targetId'
    | '/_landing/'
    | '/admin/'
    | '/profile/'
    | '/_landing/audit-target/$slug'
    | '/_landing/global-consensus/$slug'
    | '/submissions/rfc/$id'
    | '/submissions/target/$id'
    | '/_landing/global-consensus/'
    | '/my/submissions/'
    | '/share/scorecard/$targetId/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LandingRoute: typeof LandingRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  BetaWaitlistRoute: typeof BetaWaitlistRoute
  ContributorsRoute: typeof ContributorsRouteWithChildren
  GovernanceRoute: typeof GovernanceRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  MyRoute: typeof MyRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
  ReviewRoute: typeof ReviewRoute
  ScorecardRoute: typeof ScorecardRoute
  SubmissionsRoute: typeof SubmissionsRouteWithChildren
  ScoringTargetIdRoute: typeof ScoringTargetIdRoute
  ShareScorecardTargetIdUserIdRoute: typeof ShareScorecardTargetIdUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submissions': {
      id: '/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorecard': {
      id: '/scorecard'
      path: '/scorecard'
      fullPath: '/scorecard'
      preLoaderRoute: typeof ScorecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributors': {
      id: '/contributors'
      path: '/contributors'
      fullPath: '/contributors'
      preLoaderRoute: typeof ContributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta-waitlist': {
      id: '/beta-waitlist'
      path: '/beta-waitlist'
      fullPath: '/beta-waitlist'
      preLoaderRoute: typeof BetaWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/scoring/$targetId': {
      id: '/scoring/$targetId'
      path: '/scoring/$targetId'
      fullPath: '/scoring/$targetId'
      preLoaderRoute: typeof ScoringTargetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/submissions': {
      id: '/profile/submissions'
      path: '/submissions'
      fullPath: '/profile/submissions'
      preLoaderRoute: typeof ProfileSubmissionsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/privacy': {
      id: '/profile/privacy'
      path: '/privacy'
      fullPath: '/profile/privacy'
      preLoaderRoute: typeof ProfilePrivacyRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/preferences': {
      id: '/profile/preferences'
      path: '/preferences'
      fullPath: '/profile/preferences'
      preLoaderRoute: typeof ProfilePreferencesRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/contributors/governance': {
      id: '/contributors/governance'
      path: '/governance'
      fullPath: '/contributors/governance'
      preLoaderRoute: typeof ContributorsGovernanceRouteImport
      parentRoute: typeof ContributorsRoute
    }
    '/_landing/manifesto': {
      id: '/_landing/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof LandingManifestoRouteImport
      parentRoute: typeof LandingRoute
    }
    '/my/submissions/': {
      id: '/my/submissions/'
      path: '/submissions'
      fullPath: '/my/submissions'
      preLoaderRoute: typeof MySubmissionsIndexRouteImport
      parentRoute: typeof MyRoute
    }
    '/_landing/global-consensus/': {
      id: '/_landing/global-consensus/'
      path: '/global-consensus'
      fullPath: '/global-consensus'
      preLoaderRoute: typeof LandingGlobalConsensusIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/submissions/target/$id': {
      id: '/submissions/target/$id'
      path: '/target/$id'
      fullPath: '/submissions/target/$id'
      preLoaderRoute: typeof SubmissionsTargetIdRouteImport
      parentRoute: typeof SubmissionsRoute
    }
    '/submissions/rfc/$id': {
      id: '/submissions/rfc/$id'
      path: '/rfc/$id'
      fullPath: '/submissions/rfc/$id'
      preLoaderRoute: typeof SubmissionsRfcIdRouteImport
      parentRoute: typeof SubmissionsRoute
    }
    '/_landing/global-consensus/$slug': {
      id: '/_landing/global-consensus/$slug'
      path: '/global-consensus/$slug'
      fullPath: '/global-consensus/$slug'
      preLoaderRoute: typeof LandingGlobalConsensusSlugRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/audit-target/$slug': {
      id: '/_landing/audit-target/$slug'
      path: '/audit-target/$slug'
      fullPath: '/audit-target/$slug'
      preLoaderRoute: typeof LandingAuditTargetSlugRouteImport
      parentRoute: typeof LandingRoute
    }
    '/share/scorecard/$targetId/$userId': {
      id: '/share/scorecard/$targetId/$userId'
      path: '/share/scorecard/$targetId/$userId'
      fullPath: '/share/scorecard/$targetId/$userId'
      preLoaderRoute: typeof ShareScorecardTargetIdUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LandingRouteChildren {
  LandingManifestoRoute: typeof LandingManifestoRoute
  LandingIndexRoute: typeof LandingIndexRoute
  LandingAuditTargetSlugRoute: typeof LandingAuditTargetSlugRoute
  LandingGlobalConsensusSlugRoute: typeof LandingGlobalConsensusSlugRoute
  LandingGlobalConsensusIndexRoute: typeof LandingGlobalConsensusIndexRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingManifestoRoute: LandingManifestoRoute,
  LandingIndexRoute: LandingIndexRoute,
  LandingAuditTargetSlugRoute: LandingAuditTargetSlugRoute,
  LandingGlobalConsensusSlugRoute: LandingGlobalConsensusSlugRoute,
  LandingGlobalConsensusIndexRoute: LandingGlobalConsensusIndexRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ContributorsRouteChildren {
  ContributorsGovernanceRoute: typeof ContributorsGovernanceRoute
}

const ContributorsRouteChildren: ContributorsRouteChildren = {
  ContributorsGovernanceRoute: ContributorsGovernanceRoute,
}

const ContributorsRouteWithChildren = ContributorsRoute._addFileChildren(
  ContributorsRouteChildren,
)

interface MyRouteChildren {
  MySubmissionsIndexRoute: typeof MySubmissionsIndexRoute
}

const MyRouteChildren: MyRouteChildren = {
  MySubmissionsIndexRoute: MySubmissionsIndexRoute,
}

const MyRouteWithChildren = MyRoute._addFileChildren(MyRouteChildren)

interface ProfileRouteChildren {
  ProfilePreferencesRoute: typeof ProfilePreferencesRoute
  ProfilePrivacyRoute: typeof ProfilePrivacyRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProfileSubmissionsRoute: typeof ProfileSubmissionsRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfilePreferencesRoute: ProfilePreferencesRoute,
  ProfilePrivacyRoute: ProfilePrivacyRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProfileSubmissionsRoute: ProfileSubmissionsRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface SubmissionsRouteChildren {
  SubmissionsRfcIdRoute: typeof SubmissionsRfcIdRoute
  SubmissionsTargetIdRoute: typeof SubmissionsTargetIdRoute
}

const SubmissionsRouteChildren: SubmissionsRouteChildren = {
  SubmissionsRfcIdRoute: SubmissionsRfcIdRoute,
  SubmissionsTargetIdRoute: SubmissionsTargetIdRoute,
}

const SubmissionsRouteWithChildren = SubmissionsRoute._addFileChildren(
  SubmissionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LandingRoute: LandingRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  BetaWaitlistRoute: BetaWaitlistRoute,
  ContributorsRoute: ContributorsRouteWithChildren,
  GovernanceRoute: GovernanceRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  MyRoute: MyRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
  ReviewRoute: ReviewRoute,
  ScorecardRoute: ScorecardRoute,
  SubmissionsRoute: SubmissionsRouteWithChildren,
  ScoringTargetIdRoute: ScoringTargetIdRoute,
  ShareScorecardTargetIdUserIdRoute: ShareScorecardTargetIdUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
